# Generated by Django 4.0.8 on 2023-10-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_logoo',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_pictures/%y/%m/%d/'),
        ),
    ]
