# Generated by Django 4.0.8 on 2023-10-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_picture_logoo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture_logoo',
            new_name='picture_logo',
        ),
    ]
